package com.gdelight.widget.adapter;

import java.util.ArrayList;
import java.util.List;

import android.content.Context;
import android.util.TypedValue;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.Filter;
import android.widget.Filterable;
import android.widget.TextView;

public class WantAutoCompleteAdapter extends ArrayAdapter<String> implements Filterable {

	private List<String> mData;
	private List<String> data = new ArrayList<String>();

	public WantAutoCompleteAdapter(Context context, int textViewResourceId) {
		super(context, textViewResourceId);
		mData = new ArrayList<String>();
	}

	@Override
	public int getCount() {
		return mData.size();
	}

	@Override
	public String getItem(int index) {
		String item = "";
		if (mData.size() != 0 && mData.size() < index) {
			item = mData.get(index);
		}
		return item;
	}

	@Override
	public Filter getFilter() {
		Filter myFilter = new Filter() {
			@Override
			protected FilterResults performFiltering(CharSequence constraint) {
				FilterResults filterResults = new FilterResults();
				
				if (data.size() == 0) {
					setData();
				}
				
				if(constraint != null && constraint.length() > 2) {

					mData = new ArrayList<String>();
					for (String d: data) {
						if (d.toUpperCase().contains(constraint.toString().toUpperCase()))
							mData.add(d);
					}

					// A class that queries a web API, parses the data and returns an ArrayList<Style>
					//StyleFetcher fetcher = new StyleFetcher();
					//try {
						//    mData = fetcher.retrieveResults(constraint.toString());
					//}
					// catch(Exception e) {}
					// Now assign the values and count to the FilterResults object
					filterResults.values = mData;
					filterResults.count = mData.size();
				}
				return filterResults;
			}

			@Override
			protected void publishResults(CharSequence contraint, FilterResults results) {
				if(results != null && results.count > 0) {
					notifyDataSetChanged();
				}
				else {
					notifyDataSetInvalidated();
				}
			}
		};
		return myFilter;
	}

	@Override
	public View getView (int position, View convertView, ViewGroup parent) {
		TextView originalView = (TextView) super.getView(position, convertView, parent); // Get the original view

		final LayoutInflater inflater = LayoutInflater.from(getContext());
		final TextView view = (TextView) inflater.inflate(android.R.layout.simple_dropdown_item_1line, parent, false);

		// Start tweaking
		view.setText(originalView.getText());
		//view.setTextColor(getResources().R.color.red);  // also useful if you have a color scheme that makes the text show up white
		view.setTextSize(TypedValue.COMPLEX_UNIT_SP, 10); // override the text size
		return view;
	}

	private void setData() {

		data.add("Amaranth (Amaranthus cruentus)");
		data.add("Arugula (Eruca sativa)");
		data.add("Beet greens (Beta vulgaris subsp. vulgaris)");
		data.add("Bok choy (Brassica rapa Chinensis group)");
		data.add("Borage greens (Borago officinalis)");
		data.add("Broccoli Rabe (Brassica rapa subsp. rapa)");
		data.add("Brussels sprout (Brassica oleracea Gemmifera group)");
		data.add("Cabbage (Brassica oleracea Capitata group)");
		data.add("Catsear (Hypochaeris radicata)");
		data.add("Celery (Apium graveolens)");
		data.add("Celtuce (Lactuca sativa var. asparagina)");
		data.add("Ceylon spinach (Basella alba)");
		data.add("Chaya (Cnidoscolus aconitifolius subsp. aconitifolius)");
		data.add("Chickweed (Stellaria)");
		data.add("Chicory (Cichorium intybus)");
		data.add("Chinese Mallow (Malva verticillata)");
		data.add("Chrysanthemum leaves (Chrysanthemum coronarium)");
		data.add("Collard greens (Brassica oleracea)");
		data.add("Corn salad (Valerianella locusta)");
		data.add("Cress (Lepidium sativum)");
		data.add("Dandelion (Taraxacum officinale)");
		data.add("Endive (Cichorium endivia)");
		data.add("Fat hen (Chenopodium album)");
		data.add("Fiddlehead (Pteridium aquilinum, Athyrium esculentum)");
		data.add("Fluted pumpkin (Telfairia occidentalis)");
		data.add("Garden Rocket (Eruca sativa)");
		data.add("Golden samphire (Inula crithmoides)");
		data.add("Good King Henry (Chenopodium bonus-henricus)");
		data.add("Greater Plantain (Plantago major)");
		data.add("Kai-lan (Gai Lan ?? Brassica rapa Alboglabra group)");
		data.add("Kale (Brassica oleracea Acephala group)");
		data.add("Komatsuna (Brassica rapa Pervidis or Komatsuna group)");
		data.add("Kuka (Adansonia spp.)");
		data.add("Lagos bologi (Talinum fruticosum)");
		data.add("Lamb's lettuce (Valerianella locusta)");
		data.add("Land cress (Barbarea verna)");
		data.add("Lettuce (Lactuca sativa)");
		data.add("Lizard's tail (Houttuynia cordata)");
		data.add("Melokhia (Corchorus olitorius, Corchorus capsularis)");
		data.add("Miner's Lettuce");
		data.add("Mizuna greens (Brassica rapa Nipposinica group)");
		data.add("Mustard (Sinapis alba)");
		data.add("Napa cabbage (Siu Choi ?? Brassica rapa Pekinensis group)");
		data.add("New Zealand Spinach (Tetragonia tetragonioides)");
		data.add("Orache (Atriplex hortensis)");
		data.add("Pak choy (Bok Choy ?? Brassica rapa Chinensis group)");
		data.add("Paracress (Acmella oleracea)");
		data.add("Pea sprouts/leaves (Pisum sativum)");
		data.add("Poke (Phytolacca americana)");
		data.add("Radicchio (Cichorium intybus)");
		data.add("Samphire (Crithmum maritimum)");
		data.add("San Choy");
		data.add("Sculpit/Stridolo (Silene inflata)");
		data.add("Sea beet (Beta vulgaris subsp. maritima)");
		data.add("Sea kale (Crambe maritima)");
		data.add("Sierra Leone bologi (Crassocephalum spp.)");
		data.add("Soko (Celosia argentea)");
		data.add("Sorrel (Rumex acetosa)");
		data.add("Spinach (Spinacia oleracea)");
		data.add("Summer purslane (Portulaca oleracea)");
		data.add("Swiss chard (Beta vulgaris subsp. cicla var. flavescens)");
		data.add("Tatsoi (Brassica rapa Rosularis group)");
		data.add("Turnip greens (Brassica rapa Rapifera group)");
		data.add("Watercress (Nasturtium officinale)");
		data.add("Water spinach (Ipomoea aquatica)");
		data.add("Wheatgrass (Triticum aestivum)");
		data.add("Winter purslane (Claytonia perfoliata)");
		data.add("Yarrow (Achillea millefolium)");
		data.add("Yao Choy (Yu Choy, Rape, Brassica napus)");
		data.add("Avocado (Persea americana)");
		data.add("Bell pepper (Capsicum annuum)");
		data.add("Bitter melon/Bitter gourd (Momordica charantia)");
		data.add("Chayote (Sechium edule)");
		data.add("Cucumber (Cucumis sativus)");
		data.add("Ivy Gourd (Coccinia grandis)");
		data.add("Eggplant/Aubergine/Brinjal (Solanum melongena)");
		data.add("Luffa (Luffa cylindrica)");
		data.add("Pumpkin (Cucurbita spp.)");
		data.add("Squash (Cucurbita spp.)");
		data.add("Sweet corn aka corn; aka maize (Zea mays)");
		data.add("Sweet pepper (Capsicum annuum Grossum group)");
		data.add("Tinda (Praecitrullus fistulosus)");
		data.add("Tomatillo (Physalis philadelphica)");
		data.add("Tomato (Solanum lycopersicum var)");
		data.add("West Indian gherkin (Cucumis anguria)");
		data.add("Winter melon (Benincasa hispida)");
		data.add("Zucchini/Courgette (Cucurbita pepo)");
		data.add("Artichoke (Cynara cardunculus, C. scolymus)");
		data.add("Broccoli (Brassica oleracea)");
		data.add("Caper (Capparis spinosa)");
		data.add("Cauliflower (Brassica oleracea)");
		data.add("Courgette flowers (Cucurbita spp.)");
		data.add("Squash blossoms (Cucurbita spp.)");
		data.add("American groundnut (Apios americana)");
		data.add("Azuki bean (Vigna angularis)");
		data.add("Black-eyed pea (Vigna unguiculata subsp. unguiculata)");
		data.add("Chickpea (Cicer arietinum)");
		data.add("Common bean (Phaseolus vulgaris)");
		data.add("Drumstick (Moringa oleifera)");
		data.add("Dolichos bean (Lablab purpureus)");
		data.add("Fava bean (Vicia faba)");
		data.add("Garbanzo (Cicer arietinum)");
		data.add("Green bean (Phaseolus vulgaris)");
		data.add("Guar (Cyamopsis tetragonoloba)");
		data.add("Horse gram (Macrotyloma uniflorum)");
		data.add("Indian pea (Lathyrus sativus)");
		data.add("Lentil (Lens culinaris)");
		data.add("Lima Bean (Phaseolus lunatus)");
		data.add("Moth bean (Vigna acontifolia)");
		data.add("Mung bean (Vigna radiata)");
		data.add("Okra (Abelmoschus esculentus)");
		data.add("Pea (Pisum sativum)");
		data.add("Peanut (Arachis hypogaea)");
		data.add("Pigeon pea (Cajanus cajan)");
		data.add("Ricebean (Vigna umbellata)");
		data.add("Runner bean (Phaseolus coccineus)");
		data.add("Snap pea (Pisum sativum var. macrocarpon)");
		data.add("Snow pea (Pisum sativum var. saccharatum)");
		data.add("Soybean (Glycine max)");
		data.add("Tarwi (tarhui, chocho; Lupinus mutabilis)");
		data.add("Tepary bean (Phaseolus acutifolius)");
		data.add("Urad bean (Vigna mungo)");
		data.add("Velvet bean (Mucuna pruriens)");
		data.add("Winged bean (Psophocarpus tetragonolobus)");
		data.add("Yardlong bean (Vigna unguiculata subsp. sesquipedalis)");
		data.add("Asparagus (Asparagus officinalis)");
		data.add("Cardoon (Cynara cardunculus)");
		data.add("Celeriac (Apium graveolens var. rapaceum)");
		data.add("Celery (Apium graveolens)");
		data.add("Elephant Garlic (Allium ampeloprasum var. ampeloprasum)");
		data.add("Florence fennel (Foeniculum vulgare var. dulce)");
		data.add("Garlic (Allium sativum)");
		data.add("Kohlrabi (Brassica oleracea Gongylodes group)");
		data.add("Kurrat (Allium ampeloprasum var. kurrat)");
		data.add("Leek (Allium porrum)");
		data.add("Lotus root (Nelumbo nucifera)");
		data.add("Nopal (Opuntia ficus-indica)");
		data.add("Onion (Allium cepa)");
		data.add("Pearl onion (A. ampeloprasum var. sectivum or A. ampeloprasum 'Pearl-Onion Group)");
		data.add("Potato onion ('Aggregatum group' of Allium cepa)");
		data.add("Prussian asparagus (Ornithogalum pyrenaicum)");
		data.add("Spring Onion/Scallion (Allium wakegi)");
		data.add("Shallot (Allium cepa Aggregatum group)");
		data.add("Tree Onion (Allium × proliferum)");
		data.add("abusgata (Allium fistulosum)");
		data.add("Wild leek (Allium tricoccum)");
		data.add("Ahipa (Pachyrhizus ahipa)");
		data.add("Arracacha (Arracacia xanthorrhiza)");
		data.add("Bamboo shoot (Bambusa vulgaris and Phyllostachys edulis)");
		data.add("Beetroot (Beta vulgaris subsp. vulgaris)");
		data.add("Burdock (Arctium lappa)");
		data.add("Broadleaf arrowhead (Sagittaria latifolia)");
		data.add("Camas (Camassia)");
		data.add("Canna (Canna spp.)");
		data.add("Carrot (Daucus carota)");
		data.add("Cassava (Manihot esculenta)");
		data.add("Chinese artichoke (Stachys affinis)");
		data.add("Daikon (Raphanus sativus Longipinnatus group)");
		data.add("Earthnut pea (Lathyrus tuberosus)");
		data.add("Elephant Foot yam (Amorphophallus_paeoniifolius)");
		data.add("Ensete (Ensete ventricosum)");
		data.add("Ginger (Zingiber officinale)");
		data.add("Hamburg parsley (Petroselinum crispum var. tuberosum)");
		data.add("Horseradish (Armoracia rusticana)");
		data.add("Jerusalem artichoke (Helianthus tuberosus)");
		data.add("Jícama (Pachyrhizus erosus)");
		data.add("Mashua (Tropaeolum tuberosum)");
		data.add("Parsnip (Pastinaca sativa)");
		data.add("Pignut (Conopodium majus)");
		data.add("Potato (Solanum tuberosum)");
		data.add("Prairie turnip (Psoralea esculenta)");
		data.add("Radish (Raphanus sativus)");
		data.add("Rutabaga (Brassica napus Napobrassica group)");
		data.add("Salsify (Tragopogon porrifolius)");
		data.add("Scorzonera (Scorzonera hispanica)");
		data.add("Skirret (Sium sisarum)");
		data.add("Swede (Brassica napus Napobrassica group)");
		data.add("Sweet Potato or Kumara (Ipomoea batatas)");
		data.add("Taro (Colocasia esculenta)");
		data.add("Ti (Cordyline fruticosa)");
		data.add("Tigernut (Cyperus esculentus)");
		data.add("Turnip (Brassica rapa Rapifera group)");
		data.add("Ulluco (Ullucus tuberosus)");
		data.add("Wasabi (Wasabia japonica)");
		data.add("Water caltrop (Trapa natans) or (Trapa bicornis).");
		data.add("Water chestnut (Eleocharis dulcis)");
		data.add("Yacón (Smallanthus sonchifolius)");
		data.add("Yam (Dioscorea spp.)");
		data.add("Aonori (Monostroma spp., Enteromorpha spp.)");
		data.add("Arame (Eisenia bicyclis)");
		data.add("Carola (Callophyllis variegata)");
		data.add("Dabberlocks or badderlocks (Alaria esculenta)");
		data.add("Dulse or dillisk (Palmaria palmata)");
		data.add("Hijiki (Hizikia fusiformis)");
		data.add("Kombu (Laminaria japonica)");
		data.add("Laver (or gim) (Porphyra spp.)");
		data.add("Mozuku (Cladosiphon okamuranus)");
		data.add("Nori (Porphyra spp.)");
		data.add("Ogonori (Gracilaria spp.)");
		data.add("Sea grape (Caulerpa spp.)");
		data.add("Sea kale (Crambe maritima)");
		data.add("Sea lettuce (Ulva lactuca)");
		data.add("Wakame (Undaria pinnatifida)");
		data.add("Abiu (Pouteria caimito; Sapotaceae)");
		data.add("Açaí (Euterpe oleracea; Arecaceae), or Assai");
		data.add("Acerola (Malpighia glabra; Malpighiaceae)");
		data.add("Ackee (Blighia sapida or Cupania sapida; Sapindaceae)");
		data.add("African cherry orange (Citropsis schweinfurthii; Rutaceae)");
		data.add("African mango (Irvingia gabonensis)");
		data.add("African moringa (Moringa stenopetala; Moringaceae)");
		data.add("Ambarella (Spondias dulcis; Anacardiaceae)");
		data.add("American Black Elderberry (Sambucus canadensis; Adoxaceae)");
		data.add("American Chestnut (Castanea dentata; Fagaceae)");
		data.add("American grape");
		data.add("American Hazelnut (Corylus americana; Betulaceae)");
		data.add("American Pawpaw (Asimina triloba; Annonaceae)");
		data.add("American Persimmon (Diospyros virginiana; Ebenaceae)");
		data.add("American plum (Prunus americana; Rosaceae)");
		data.add("American Red Elderberry (Sambucus pubens; Adoxaceae)");
		data.add("American Red Raspberry (Rubus strigosus; Rosaceae)");
		data.add("Apple and crabapple (Malus)");
		data.add("Apple, Malay, see Malay apple");
		data.add("Apple, custard, see Custard apple");
		data.add("Apple, elephant, see Elephant apple");
		data.add("Apple, kei, see key apple");
		data.add("Apple, mammee, see mammee apple");
		data.add("Apricot (Prunus armeniaca or Armeniaca vulgaris)");
		data.add("Araza (Eugenia stipitata)");
		data.add("Arhat (Siraitia grosvenorii; Cucurbitaceae)");
		data.add("Atemoya (Annona cherimola × Annona squamosa; Annonaceae)");
		data.add("Atherton Raspberry (Rubus probus; Rosaceae)");
		data.add("Avocado (Persea americana; Lauraceae)");
		data.add("Babaco (Carica pentagona; Caricaceae)");
		data.add("Bacupari (Garcinia gardneriana)");
		data.add("Bacuri (Platonia esculenta; Guttiferae)");
		data.add("Bael, or Woodapple (Aegle marmelos; Rutaceae)");
		data.add("Banana (Musacea spp.; Musaceae)");
		data.add("Barbadine (granadilla; maracujá-açu in Portuguese)");
		data.add("Barbados Cherry, see acerola");
		data.add("Batuan (Garcinia morella)");
		data.add("Beach Plum (Prunus maritima; Rosaceae)");
		data.add("Bearberry (Arctostaphylos spp.)");
		data.add("Betel Nut (“Areca catechu”; Arecaceae)");
		data.add("Bignay (Antidesma bunius; Euphorbiaceae)");
		data.add("Bilberry or whortleberry (Vaccinium spp.)");
		data.add("Bilimbi (Averrhoa bilimbi; Oxalidaceae)");
		data.add("Biribi (Rollinia deliciosa; Annonaceae)");
		data.add("Bitter melon");
		data.add("Black Apple (Planchonella australis; Sapotaceae)");
		data.add("Black cherry (Prunus serotina; Rosaceae)");
		data.add("Black raspberry (Rubus occidentalis or Rubus leucodermis; Rosaceae)");
		data.add("Black Mulberry (Morus nigra; Moraceae)");
		data.add("Black Sapote (Diospyros digyna)");
		data.add("Black Walnut (Juglans nigra; Juglandaceae)");
		data.add("Blackberry");
		data.add("berry");
		data.add("senberry");
		data.add("llieberry");
		data.add("berry (genus Rubus)");
		data.add("Blood Orange");
		data.add("Blue tongue (Melastoma affine; Melastomataceae)");
		data.add("Blueberry (Vaccinium, sect. Cyanococcus; Ericaceae)");
		data.add("Bolivian coconut (Parajubaea torallyi)");
		data.add("Bolwarra (Eupomatia laurina; Eupomatiaceae)");
		data.add("Boquila (Boquila trifoliata ; Lardizabalaceae)");
		data.add("Bottle Gourd also known as Calabash (Lagenaria siceraria; Cucurbitaceae)");
		data.add("Brazilian Guava (Psidium guineense; Myrtaceae)");
		data.add("Breadnut (Artocarpus camansi; Moraceae)");
		data.add("Breadnut, Mayan, see Mayan breadnut");
		data.add("Broad-leaf Bramble (Rubus moluccanus; Rosaceae)");
		data.add("Buah Badai (Canarium odontophyllum; Burseraceae)");
		data.add("Buddha's Hand");
		data.add("Buffaloberry (Shepherdia argentea; Elaeagnaceae)");
		data.add("Burdekin Plum (Pleiogynium timorense; Anacardiaceae)");
		data.add("Burmese grape, or Latka (Baccaurea sapida; Phyllanthaceae)");
		data.add("Bush tomato (Certain Solanum species; Solanaceae)");
		data.add("Button Mangosteen (Garcinia prainiana)");
		data.add("Caimito (Chrysophyllum_cainito; Sapotaceae)");
		data.add("Calabash Tree (Crescentia cujete)");
		data.add("Calamondin (Citrofortunella Microcarpa)");
		data.add("Calamansi (×Citrofortunella Mitis))");
		data.add("CamuCamu (Myrciaria dubia; Myrtaceae)");
		data.add("Canary melon");
		data.add("Canistel (Pouteria campechiana; Sapotaceae)");
		data.add("Cantaloupe");
		data.add("Cape Gooseberry (Physalis peruviana; Solanaceae)");
		data.add("Capuli cherry (Prunus salicifolia, Prunus capuli or Prunus serotina subsp. capuli); Rosaceae)");
		data.add("Carambola (Averrhoa carambola; Oxalidaceae)");
		data.add("Cardón (Pachycereus pringlei; Cactaceae)");
		data.add("Carob (Ceratonia siliqua; Fabaceae)");
		data.add("Cashew apple (Anacardium occidentale)");
		data.add("Cassabanana (Sicana odorifera; Cucurbitaceae)");
		data.add("Cattley Guava (Psidium cattleianum; Myrtaceae)");
		data.add("Cawesh (Annona scleroderma; Annonaceae)");
		data.add("Cedar Bay cherry (Eugenia carissoides; Myrtaceae)");
		data.add("Ceriman (Monstera deliciosa; Araceae)");
		data.add("Cereus peruvianus");
		data.add("Ceylon gooseberry (Dovyalis hebecarpa; Flacourtiaceae");
		data.add("Charichuelo (Garcinia intermedia)");
		data.add("Chayote (Sechium edule; Cucurbitaceae)");
		data.add("Che (Cudrania tricuspidata; Moraceae)");
		data.add("rania");
		data.add("nese Mulberry");
		data.add("rang");
		data.add("darin Melon Berry");
		data.add("kworm Thorn");
		data.add("Chempedak or Champedak (Artocarpus integer; Moraceae)");
		data.add("Chenet (guinep or ackee; pitomba-das-Guinas in Portuguese)");
		data.add("Cherimoya (Annona cherimola; Annonaceae)");
		data.add("Cherry, sweet, black, sour, and wild species (Prunus avium, Prunus serotina, Prunus cerasus, and others)");
		data.add("Cherry ballart (Exocarpus cupressiformis; Santalaceae)");
		data.add("Cherry of the Rio Grande (Eugenia aggregata; Myrtaceae)");
		data.add("Chilean guava (Psidium cattleianum;");
		data.add("i (Myrtaceae)");
		data.add("Chinese jujube (Ziziphus zizyphus; Rhamnaceae)");
		data.add("Chinese Olive (Canarium album; Burseraceae)");
		data.add("Chinese Quince (Pseudocydonia sinensis)");
		data.add("Chokeberry (Aronia)");
		data.add("Chokecherry (Prunus virginiana)");
		data.add("Chupa-Chupa (Quararibea cordata; Malvaceae)");
		data.add("Citron (Citrus medica)");
		data.add("Clementine (Citrus reticulata var. clementine),");
		data.add("Cloudberry (Rubus chamaemorus)");
		data.add("Cluster fig (Ficus racemosa; Moraceae)");
		data.add("Cocky apple (Planchonia careya)");
		data.add("Coco Plum (Chrysobalanus icaco; Chrysobalanaceae)");
		data.add("Cocona (Solanum sessilifolium; Solanaceae)");
		data.add("Coconut (Cocos nucifera; Arecaceae)");
		data.add("Cocoplum (Chrysobalanus icaco; Chrysobalanaceae)");
		data.add("Coffee ('coffee cherries' surround the better-known 'bean')");
		data.add("Cola nut (Cola acuminata; Sterculiaceae)");
		data.add("Common apple-berry (Billardiera scandens; Pittosporaceae)");
		data.add("Conkerberry (Carissa lanceolata; Apocynaceae)");
		data.add("Cornelian cherry (Cornus mas; Cornaceae)");
		data.add("Costa Rican Guava (Psidium friedrichsthalianum; Myrtaceae)");
		data.add("Cranberry (Vaccinium spp.)");
		data.add("Crowberry (Empetrum spp.)");
		data.add("Cupuaçu (Theobroma grandiflorum; Malvaceae)");
		data.add("Currant (Ribes spp.; Grossulariaceae)");
		data.add("Curry-leaf Tree (Murraya koenigii; Rutaceae)");
		data.add("Custard Apple (Annona reticulata; Annonaceae)");
		data.add("lock's Heart");
		data.add("Damson plum (Prunus domestica subsp. insititia; Rosaceae)");
		data.add("Date (Phoenix dactylifera; Arecaceae)");
		data.add("Date plum (Diospyros lotus; Ebenaceae)");
		data.add("Davidson's plum (Cunoniaceae)");
		data.add("Dead Man's Fingers (Blue Bean, Blue Sausage Fruit,Decaisnea fargesii)");
		data.add("Desert banana (Marsdenia australis)");
		data.add("Desert fig (Ficus platypoda; Moraceae)");
		data.add("Desert lime (Citrus glauca; Rutaceae)");
		data.add("Dodder laurel (Cassytha melantha)");
		data.add("Doubah (Marsdenia australis; Apocynaceae)");
		data.add("Double Coconut or Coco-de-mer(Lodoicea maldivica; Arecaceae)");
		data.add("Dragonfruit / Pitaya (Hylocereus spp.; Cactaceae)");
		data.add("Duku (Lansium domesticum; Meliaceae)");
		data.add("Durian (Durio zibethicus; Malvaceae)");
		data.add("Eastern May Hawthorn (Crataegus aestivalis)");
		data.add("Elderberry (Sambucus; Caprifoliaceae)");
		data.add("Elephant Apple (Dillenia indica; Dilleniaceae)");
		data.add("Emblica, see Indian gooseberry");
		data.add("Emu Apple (Owenia acidula; Meliaceae)");
		data.add("Emu berry (Grewia retusifolia)");
		data.add("Falberry (Vaccinium spp.)");
		data.add("False-mastic (Sideroxylon foetidissimum; Sapotaceae)");
		data.add("Feijoa, see pineapple guava");
		data.add("Fibrous Satinash (Syzygium fibrosum; Myrtaceae)");
		data.add("Fig (Ficus spp. Moraceae)");
		data.add("Finger Lime (Citrus australasica; Rutaceae)");
		data.add("Florida strangler fig (Ficus aurea; Moraceae)");
		data.add("Forest strawberries, Fragaria vesca");
		data.add("Gac");
		data.add("Galia melon");
		data.add("Gambooge (Garcinia cambogia; Clusiaceae)");
		data.add("Genip (Melicoccus bijugatus; Sapindaceae)");
		data.add("Giant Colombian blackberry (Rubus macrocarpus)");
		data.add("Giant Granadilla (Passiflora quadrangularis; Passifloraceae)");
		data.add("Gooseberry (Ribes spp.; Grossulariaceae)");
		data.add("Gooseberry, Ceylon");
		data.add("Gooseberry, Indian");
		data.add("Gooseberry, Otaheite");
		data.add("Gooseberry, cape");
		data.add("Goumi (Elaeagnus multiflora; Elaeocarpaceae)");
		data.add("Governor’s Plum (Flacourtia indica; Flacourtiaceae)");
		data.add("Granadilla, Montessa, see Montessa granadilla");
		data.add("Granadilla, yellow");
		data.add("Grape, called raisin, sultana when it is dried. (Vitis spp.; Vitaceae)");
		data.add("Grapefruit (Citrus × paradisi; Rutaceae)");
		data.add("Greengage, a cultivar of the plum");
		data.add("Ground Plum (Astragalus crassicarpus; Fabaceae)");
		data.add("und-plum milk-vetch");
		data.add("Grumichama (Eugenia brasiliensis; Myrtaceae)");
		data.add("Guanabana (Annona muricata; Annonaceae)");
		data.add("Guarana (Paullinia cupana; Sapindaceae)");
		data.add("Guava (Psidium guajava; Myrtaceae)");
		data.add("Guava, Cattley, see Cattley guava");
		data.add("Guava, Chilean, see Chilean guava");
		data.add("Guava, Costa Rican, see Costa Rican guava");
		data.add("Guava, pineapple, see pineapple guava");
		data.add("Guava, purple, see purple guava");
		data.add("Guava, strawberry, see strawberry guava");
		data.add("Guavaberry/Rumberry; (Myrciaria floribunda; Myrtaceae)");
		data.add("Hackberry (Celtis spp.; Cannabaceae)");
		data.add("Hairless rambutan");
		data.add("Hardy Kiwi (Actinidia arguta; Actinidiaceae family)");
		data.add("Hawthorn (Crataegus and Rhaphiolepis)");
		data.add("Hog Plum (taperebá in Portuguese)");
		data.add("Honeydew");
		data.add("Honeysuckle[6]");
		data.add("Horned melon (Cucumis metuliferus; Cucurbitaceae)");
		data.add("Huckleberry (Vaccinium spp.)");
		data.add("Huito (Genipa americana; Rubiaceae)");
		data.add("Ice Cream Bean (Inga edulis)");
		data.add("Ilama (Annona diversifolia; Annonaceae)");
		data.add("Illawarra Plum (Podocarpus elatus; Podocarpaceae)");
		data.add("Imbe (Garcinia livingstonei)");
		data.add("Indian almond");
		data.add("Indian fig");
		data.add("Indian gooseberry (Phyllanthus emblica/Emblica officinalis; Euphorbiaceae)");
		data.add("Indian jujube (Ziziphus mauritiana; Rhamnaceae)");
		data.add("Indian prune (Flacourtia rukan; Flacourtiaceae)");
		data.add("Jabuticaba (Myrciaria cauliflora; Myrtaceae)");
		data.add("zilian Grape Tree");
		data.add("Jackfruit (Artocarpus heterophyllus Moraceae)");
		data.add("gka");
		data.add("Jambul (Syzygium cumini; Myrtaceae)");
		data.add("Japanese Persimmon, or Sharon fruit (Diospyros kaki; Ebenaceae)");
		data.add("Jatobá (Hymenae coubaril; Leguminosae) Caesalpinioideae)");
		data.add("Jelly Palm (Butia capitata)");
		data.add("Jocote, also called Jamaica Plum");
		data.add("Jujube (Ziziphus zizyphus; Rhamnaceae)");
		data.add("Jujube, Chinese, see Chinese jujube");
		data.add("Jujube, Indiana, see Indian jujube");
		data.add("Juniper berry (Juniperus spp.)");
		data.add("Kabosu (Citrus Sphaerocarpa) Rutaceae");
		data.add("Kaffir lime (Citrus hystix)");
		data.add("Kahikatea (Dacrycarpus dacrydioides)");
		data.add("Kakadu lime (Citrus gracilis; Rutaceae)");
		data.add("Kakadu plum (Terminalia ferdinandiana; Combretaceae)");
		data.add("Kandis (Garcinia forbesii; Clusiaceae)");
		data.add("Kapok (Ceiba pentandra; Bombacaceae)");
		data.add("Karkalla (Carpobrotus rossii; Aizoaceae)");
		data.add("Karonda (Carissa carandas; Apocynaceae)");
		data.add("Kei apple (Dovyalis caffra; Flacourtiaceae)");
		data.add("Kepel fruit (Stelechocarpus burahol; Annonaceae)");
		data.add("Keule (Gomortega keule; Gomortegaceae)");
		data.add("Key Lime (Citrus aurantifolia)");
		data.add("Kitembilla (Dovyalis hebecarpa; Flacourtiaceae)");
		data.add("Kiwano, see horned melon");
		data.add("Kiwifruit (Actinida spp.; Actinidiaceae)");
		data.add("Korlan");
		data.add("Kumquat (Fortunella spp.)");
		data.add("Kumquat, meiwa, see meiwa kumquat");
		data.add("Kumquat, nagami, see nagami kumquat");
		data.add("Kundong (Garcinia sp.; Clusiaceae)");
		data.add("Kutjera (Solanum centrale; Solanaceae)");
		data.add("Kwai Muk (Artocarpus hypargyraea; Moraceae)");
		data.add("Lady apple (Syzygium suborbiculare; Myrtaceae)");
		data.add("Lakoocha (Artocarpus lakoocha; Moraceae)");
		data.add("Langsat (Lansium domesticum)");
		data.add("Lanzones (Lansium domesticum; Meliaceae)");
		data.add("Lapsi (Choerospondias axillaris Roxb. Anacardiaceae)");
		data.add("Lardizabala (Lardizabala biternata; Lardizabalaceae)");
		data.add("Lemon (Citrus limon)");
		data.add("Lemon aspen (Acronychia acidula; Rutaceae)");
		data.add("Leucaena");
		data.add("Lillypilly (Acmena spp., Syzygium spp.)");
		data.add("Little gooseberry tree (Buchanania arborescens; Anacardiaceae)");
		data.add("Lime");
		data.add("Limeberry (Trifasia trifolia; Rutaceae)");
		data.add("Limequat (Citrus aurantifolia × Fortunella spp.; Rutaceae)");
		data.add("Lingonberry (Vaccinium vitis-idaea)");
		data.add("Loganberry (Rubus loganobaccus)");
		data.add("Longan (Dimocarpus longan or Euphoria longana; Sapindaceae)");
		data.add("Loquat (Eriobotrya japonica; Rosaceae)");
		data.add("Louvi (Flacourtia inermis; Flacourtaceae)");
		data.add("Lúcuma (Pouteria campechiana; Sapotaceae)");
		data.add("Lychee (Litchi chinensis; Sapindaceae)");
		data.add("Ma-praang (Bouea macrophylla; Anacardiaceae)");
		data.add("Mabolo (Diospyros discolor; Ebenaceae)");
		data.add("Macadamia (Macadamia integrifolia; Proteaceae)");
		data.add("Macadamia, rough shell, see rough shell macadamia");
		data.add("Madrono (Rheedia acuminata; Guttiferae)");
		data.add("Malabar plum (Syzygium jambos; Myrtaceae)");
		data.add("Malay Apple (Syzygium malaccense; Myrtaceae)");
		data.add("Mamey Sapote (Pouteria sapota; Sapotaceae)");
		data.add("Mammee Apple (Mammea americana; Guttiferae)");
		data.add("Mamoncillo (Melicoccus bijugatus; Sapindaceae)");
		data.add("Mandarin (Citrus reticulata)");
		data.add("Mangaba (Hancornia speciosa; Apocynaceae)");
		data.add("Mango (Mangifera indica; Anacardiaceae)");
		data.add("Mangosteen (Garcinia mangostana; Guttiferae)");
		data.add("Manila tamarind (Pithecellobium dulce; Leguminosae)");
		data.add("Manoao (Manoao colensoi)");
		data.add("Maqui (Aristotelia chilensis; Elaeocarpaceae)");
		data.add("Marang");
		data.add("Marula (Sclerocarya birrea)");
		data.add("Breadnut, Mayan (Brosimum alicastrum; Moraceae)");
		data.add("Mayapple (Podophyllum spp.; Berberidaceae)");
		data.add("Mayhaw, see Eastern may hawthorn");
		data.add("Maypop (Passiflora incarnata; Passifloraceae)");
		data.add("Medlar (Mespilus germanica)");
		data.add("Meiwa Kumquat (Fortunella japonica; Rutaceae)");
		data.add("Melinjo");
		data.add("Melon pear");
		data.add("Midyim (Austromyrtus dulcis; Myrtaceae)");
		data.add("Miracle Fruit (Synsepalum dulcificum; Sapotaceae)");
		data.add("Mock Strawberry or Indian Strawberry (Potentilla indica; Rosaceae)");
		data.add("Mombin, purple, see purple mombin");
		data.add("Mombin, red, see red mombin");
		data.add("Mombin, yellow, see yellow mombin");
		data.add("Monkey Jackfruit (Artocarpus rigidus; Moraceae)");
		data.add("Monkey Tamarind (Inga edulis; Leguminosae)");
		data.add("Monstera (Monstera deliciosa; Araceae)");
		data.add("it-leaf Philodendron");
		data.add("Montessa Granadilla (Passiflora platyloba; Passifloraceae)");
		data.add("Mora Común (Rubus adenotrichus)");
		data.add("Mora de Castilla (Rubus glaucus)");
		data.add("Morinda");
		data.add("Morinda citrifolia");
		data.add("Mortiño, or Andean blueberry (Vaccinium floribundum)");
		data.add("Mountain pepper (Tasmannia spp.; Winteraceae )");
		data.add("Mountain Soursop (Annona montana; Annonaceae)");
		data.add("Mulberry (Morus spp.; Moraceae)");
		data.add("Munydjudj, see wild plum");
		data.add("Mundu (Garcinia dulcis)");
		data.add("Muntries (Kunzea pomifera; Myrtaceae)");
		data.add("Muscadine (Vitis rotundifolia; Vitaceae)");
		data.add("Muskmelon");
		data.add("Naartjie (Citrus reticulata, Citrus nobilis)");
		data.add("Nagami Kumquat (Fortunella margarita; Rutaceae)");
		data.add("Nageia (Nageia spp.)");
		data.add("Nance (Byrsonima crassifolia; Malpighiaceae)");
		data.add("Nannyberry or sheepberry (Viburnum spp.; Caprifoliaceae)");
		data.add("Naranjilla (Solanum quitoense; Solanaceae)");
		data.add("Native currant (Acrotriche depressa; Ericaceae)");
		data.add("Native gooseberry (Physalis minima; Solanaceae)");
		data.add("Native raspberry (Rubus parviflorus)");
		data.add("Nectarine, see peach");
		data.add("Neem (Azadirachta indica; Meliaceae)");
		data.add("Néré (Parkia biglobosa)");
		data.add("Nonda plum (Parinari nonda)");
		data.add("Noni (Morinda citrifolia; Rubiaceae)");
		data.add("Nungu (Borassus flabellifer; Arecaceae)");
		data.add("Nutmeg (Myristica fragrans; Myristicaceae)");
		data.add("Oil Palm (Elaeis guineensis; Arecaceae)");
		data.add("Olive");
		data.add("Orange, sweet (Citrus sinensis)");
		data.add("Orange sour (Citrus aurantium)");
		data.add("Oregon grape (Mahonia aquifolium; Berberidaceae)");
		data.add("Oroblanco (Citrus paradisi C. grandis) Rutaceae");
		data.add("Otaheite gooseberry (Phyllanthus acidus; Phyllanthaceae)");
		data.add("Palmyra Palm/Toddy Palm (Borassus flabellifer; Arecaceae)");
		data.add("Papaya (Carica papaya; Caricaceae)");
		data.add("Passion fruit or Granadilla (Passifloraceae)");
		data.add("Pawpaw (Asimina triloba; Annonaceae)");
		data.add("aya (Carica papaya; Caricaceae)");
		data.add("Peach");
		data.add("tarine (Prunus persica)");
		data.add("Peach palm (Bactris gasipaes; Arecaceae)");
		data.add("Peanut (Arachis hypogaea; Fabaceae)");
		data.add("Peanut butter fruit (Bunchosia argentea; Malpighiaceae)");
		data.add("Pear, European and Asian species (Pyrus)");
		data.add("Pecan (Carya illinoinensis or illinoensis; Juglandaceae)");
		data.add("Pepino (Solanum muricatum)");
		data.add("Pequi (Caryocar brasiliensis; Caryocaraceae)");
		data.add("Persian lime");
		data.add("iti lime.");
		data.add("Persimmon, American, see American persimmon");
		data.add("Persimmon, oriental, see Oriental persimmon");
		data.add("Peumo (Cryptocarya alba; Lauraceae)");
		data.add("Phalsa (Grewia subinaequalis; Tiliaceae)");
		data.add("Pigeon pea");
		data.add("Pigeon plum (Coccoloba diversifolia; Polygonaceae)");
		data.add("Pigface (Carpobrotus glaucescens; Aizoaceae)");
		data.add("Pili Nut (Canarium ovatum; Burseraceae)");
		data.add("Pindo Palm (Butia Capitata; Arecaceae)");
		data.add("Pineapple (Ananas comosus ; Bromeliaceae)");
		data.add("Pineapple guava (Feijoa sellowiana; Myrtaceae)");
		data.add("Pink-flowered Native Raspberry (Rubus parvifolius; Rosaceae)");
		data.add("Pistachio (Pistacia vera; Anacardiaceae)");
		data.add("Pitaya, see Dragon fruit");
		data.add("Pitomba (Eugenia luschnathiana or Talisia esculenta)");
		data.add("Plum");
		data.add("nes");
		data.add("Pois doux (Inga edulis, ice-cream bean, or inga-cipó in Portuguese)");
		data.add("Pomegranate (Punica granatum; Punicaceae)");
		data.add("Pomelo (also known as the shaddock) (Citrus maxima)");
		data.add("Pommecythère or pomcité (Spondias cytherea)");
		data.add("Pommerac (Eugenia malaccensis)");
		data.add("Pond-apple (Annona glabra; Annonaceae)");
		data.add("Prickly pear (Opuntia spp.; Cactaceae)");
		data.add("Pulasan (Nephelium mutabile; Sapindaceae)");
		data.add("Pummelo (Citrus grandis; Rutaceae)");
		data.add("Pumpkin (Cucurbita spp.)");
		data.add("Pupunha (Bactris gasipaes; Arecaceae)");
		data.add("Purple apple-berry (Billarderia longiflora; Pittosporaceae)");
		data.add("Purple granadilla (Passiflora edulis f edulis; Passifloraceae)");
		data.add("Purple Guava (Psidium rufum; Myrtaceae)");
		data.add("Purple Mombin (Spondias purpurea; Anacardiaceae)");
		data.add("Quandong (Santalum acuminatum; Santalaceae)");
		data.add("Queensland Ebony (Diospyros humilis)");
		data.add("Quince (Cydonia oblonga and Chaenomeles)");
		data.add("Raisin tree (Hovenia dulcis, Rhamnaceae)");
		data.add("Rambutan (Nephelium lappaceum; Sapindaceae)");
		data.add("Raspberry, several species (genus Rubus)");
		data.add("Red granadilla (Passiflora coccinea; Passifloraceae)* Red Mombin (Spondias purpurea; Anacardiaceae)");
		data.add("Red Mombin (Spondias purpurea; Anacardiaceae)");
		data.add("Red Mulberry (Morus rubra)");
		data.add("Rhubarb (Rheum rhaponticum; Polygonaceae)");
		data.add("Riberry (Syzygium luehmannii; Myrtaceae)");
		data.add("nese Apple");
		data.add("Rimu (Dacrydium cupressinum)");
		data.add("Rollinia (Rollinia mucosa; Annonaceae)");
		data.add("Rose Apple (Syzygium jambos; Myrtaceae)");
		data.add("Rose hip, the fruitlike base of roses (Rosa)");
		data.add("Rose-leaf Bramble (Rubus rosifolius; Rosaceae)");
		data.add("Rose myrtle (Archirhodomyrtus beckleri; Myrtaceae)");
		data.add("Rough Shell Macadamia (Macadamia tetraphylla; Proteaceae)");
		data.add("Rowan (Sorbus)");
		data.add("Safou (Dacryodes edulis)");
		data.add("Sageretia (Sageretia theezans; Rhamnaceae)");
		data.add("Saguaro (Carnegiea gigantea; Cactaceae)");
		data.add("Salak (Salacca edulis; Arecaceae)");
		data.add("Salal (Gaultheria shallon; Ericaceae)");
		data.add("Salmonberry (Rubus spectabilis)");
		data.add("Sandpaper Fig (Ficus coronata; Moraceae)");
		data.add("Santol (Sandoricum koetjape; Meliaceae)");
		data.add("Sapote, see mamey");
		data.add("Sapodilla (Manilkara zapota; Sapotaceae)");
		data.add("Satinash, fibrous, see #fibrous_satinash#fibrous satinash");
		data.add("Saskatoonberry (Amelanchier alnifolia, Rosaceae)");
		data.add("Saw Palmetto (Serenoa repens; Arecaceae)");
		data.add("Sea-buckthorn (Hippophae rhamnoides; Elaeagnaceae)");
		data.add("Sea Grape (Coccoloba uvifera; Polygonaceae)");
		data.add("Serviceberry or Saskatoon (Amelanchier)");
		data.add("Shipova (× Sorbopyrus auricularis)");
		data.add("Small-leaf tamarind (Diploglottis campbellii; Sapindaceae)");
		data.add("Snow berry (Gaultheria hispida; Ericaceae)");
		data.add("Soncoya (Annona diversifolia; Annonaceae)");
		data.add("Service tree (Sorbus domestica)");
		data.add("Soursop (Annona muricata; Annonaceae), also called guanabana");
		data.add("Southern Crabapple (Malus angustifolia; Rosaceae)");
		data.add("Spanish lime (Melicoccus bijugatus; Sapindaceae)");
		data.add("Spanish tamarind (Vangueria madagascariensis)");
		data.add("Spiny Monkey-orange (Strychnos spinosa)");
		data.add("Star Apple (Chrysophyllum cainito; Chrysobalanaceae)");
		data.add("Starfruit, see carambola");
		data.add("Strawberry (Fragaria)");
		data.add("Strawberry Guava (Psidium littorale; Myrtaceae)");
		data.add("Strawberry myrtle, see ugni");
		data.add("Strawberry Pear");
		data.add("Sugar Apple (Annona squamosa; Annonaceae); ata in Portuguese");
		data.add("Surinam Cherry (Eugenia uniflora; Myrtaceae)");
		data.add("zilian Cherry");
		data.add("enne Cherry");
		data.add("anga");
		data.add("Sweet apple-berry (Billarderia cymosa; Pittosporaceae)");
		data.add("Sweet Granadilla (Passiflora ligularis; Passifloraceae)");
		data.add("Sweet Lemon (Citrus limetta)");
		data.add("Sweet orange");
		data.add("Sweet pepper");
		data.add("Sweetsop (Annona squamosa; Annonaceae)");
		data.add("Sycamore fig (Ficus sycomorus. Moraceae)");
		data.add("Tahitian apple (Spondias dulcis)");
		data.add("Tamarillo or Tree Tomato (Cyphomandra betacea; Solanaceae)");
		data.add("Tamarind (Tamarindus indica; Leguminosae)");
		data.add("Tangerine, and similar");
		data.add("Tanjong (Mimusops elengi; Sapindaceae)");
		data.add("Texas Persimmon (Diospyros texana; Ebenaceae)");
		data.add("Thimbleberry (Rubus parviflorus)");
		data.add("Totara (Podocarpus totara)");
		data.add("Toyon (Heteromeles arbutifolia; Rosaceae)");
		data.add("Tropical Almond (Terminalia catappa; Combretaceae)");
		data.add("Ugni (Ugni molinae; Myrtaceae)");
		data.add("Vanilla (Vanilla planifolia; Orchidaceae)");
		data.add("Velvet Tamarind (Dialium indum; Leguminosae)");
		data.add("Wampee (Clausena lansium; Rutaceae)");
		data.add("Water Apple (Syzygium aqueum; Myrtaceae)");
		data.add("Watermelon (Citrullus lanatus)");
		data.add("Wax Gourd, or winter melon (Benincasa hispida)");
		data.add("Wax jambu (Syzygium samarangense; Myrtaceae)");
		data.add("West Indian cherry, see acerola");
		data.add("White aspen (Acronychia oblongifolia; Rutaceae)");
		data.add("White Mulberry (Morus alba)");
		data.add("White Sapote (Casimiroa edulis; Rutaceae)");
		data.add("Whortleberry, see bilberry");
		data.add("Wild grape (Ampelocissus acetosa)");
		data.add("Wild orange (Capparis mitchellii; Capparaceae)");
		data.add("Wild peach (Terminalia carpentariae)");
		data.add("Wild plum (munydjudj) (Buchanania obovata)");
		data.add("Wild plum (Santalum lanceolatum)");
		data.add("Wild Mangosteen (Garcinia indica)");
		data.add("|Wineberry (Rubus phoenicolasius)");
		data.add("Wolfberry (Lycium barbarum, Lycium spp.; Solanaceae)");
		data.add("Wongi (Manilkara kaukii; Sapotaceae)");
		data.add("Wood Apple (Feronia limonia; Rutaceae)");
		data.add("Yangmei (Myrica rubra; Myricaceae)");
		data.add("Yantok, or rattan fruit (Calamus manillensis)");
		data.add("Yellow Granadilla (Passiflora edulis f flavicarpa; Passifloraceae)");
		data.add("Yellow Mombin (Spondias mombin; Anacardiaceae)");
		data.add("Yellow plum (Ximenia americana; Olacaceae)");
		data.add("Yew (Taxus baccata; Taxaceae)");
		data.add("Youngberry");
		data.add("Zig Zag Vine (Melodurum leichhardtii; Annonaceae)");
		data.add("Ziziphus, see Jujube");
		data.add("Amaranth");
		data.add("Arrowroot");
		data.add("Banana Squash");
		data.add("Bell Peppers");
		data.add("Black Eyed Peas");
		data.add("Black Radish");
		data.add("Bok Choy");
		data.add("Broccoflower");
		data.add("Broccolini");
		data.add("Burdock Root");
		data.add("Cabbage");
		data.add("Carrots");
		data.add("Celeriac (Celery Root)");
		data.add("Celery");
		data.add("Cherry Tomatoes");
		data.add("Chinese Eggplants");
		data.add("Galangal Root");
		data.add("Leek");
		data.add("Lettuce");
		data.add("Mushrooms");
		data.add("Olives");
		data.add("Onions");
		data.add("Parsnips");
		data.add("Pearl Onions");
		data.add("Potatoes");
		data.add("Rutabagas");
		data.add("Salad Savoy");
		data.add("Snow Peas");
		data.add("Wasabi Root");
		data.add("Yucca Root");
		data.add(" Artichokes ");
		data.add("Asparagus ");
		data.add("Belgian Endive");
		data.add("Broccoli");
		data.add("Butter Lettuce");
		data.add("Cactus");
		data.add("Chayote Squash ");
		data.add("Chives");
		data.add("Collard Greens");
		data.add("Corn");
		data.add("Fava Beans");
		data.add("Fennel");
		data.add("Fiddlehead Ferns");
		data.add("Green Beans");
		data.add("Manoa Lettuce");
		data.add("Morel Mushrooms");
		data.add("Mustard Greens");
		data.add("Pea Pods");
		data.add("Peas");
		data.add("Purple Asparagus");
		data.add("Radicchio");
		data.add("Ramps");
		data.add("Red Leaf Lettuce");
		data.add("Rhubarb ");
		data.add("Snow Peas");
		data.add("Sorrel");
		data.add("Spinach");
		data.add("Spring Baby Lettuce");
		data.add("Swiss Chard");
		data.add("Vidalia Onions");
		data.add("Watercress");
		data.add(" Acorn Squash");
		data.add("Belgian Endive");
		data.add("Black Salsify");
		data.add("Broccoli");
		data.add("Brussels Sprouts");
		data.add("Butter Lettuce");
		data.add("Buttercup Squash");
		data.add("Butternut Squash");
		data.add("Cauliflower");
		data.add("Chayote Squash");
		data.add("Chinese Long Beans");
		data.add("Delicata Squash");
		data.add("Diakon Radish");
		data.add("Endive");
		data.add("Garlic");
		data.add("Ginger");
		data.add("Jalapeno Peppers");
		data.add("Jerusalem Artichoke");
		data.add("Kohlrabi");
		data.add("Pumpkin");
		data.add("Radicchio");
		data.add("Sweet Dumpling Squash");
		data.add("Sweet Potatoes");
		data.add("Swiss Chard");
		data.add("Turnips");
		data.add("Winter Squash");
		data.add("Belgian Endive ");
		data.add("Brussels Sprouts");
		data.add("Buttercup Squash");
		data.add("Collard Greens");
		data.add("Delicata Squash");
		data.add("Kale");
		data.add("Leeks");
		data.add("Sweet Dumpling Squash");
		data.add("Sweet Potatoes");
		data.add("Turnips");
		data.add(" Beets");
		data.add("Bell Peppers");
		data.add("Butter Lettuce");
		data.add("Chayote Squash");
		data.add("Chinese Long Beans");
		data.add("Corn");
		data.add("Crookneck Squash");
		data.add("Cucumbers");
		data.add("Eggplant");
		data.add("Endive");
		data.add("Garlic");
		data.add("Green Beans");
		data.add("Green Soybeans (Edamame)");
		data.add("Jalapeno Peppers");
		data.add("Lima Beans");
		data.add("Manoa Lettuce");
		data.add("Okra");
		data.add("Peas");
		data.add("Radishes");
		data.add("Shallots");
		data.add("Sugar Snap Peas");
		data.add("Summer Squash");
		data.add("Tomatillo");
		data.add("Tomatoes");
		data.add("Winged Beans");
		data.add("Yukon Gold Potatoes");
		data.add("Zucchini");
		data.add("Apple");
		data.add("Apricot, Dried");
		data.add("Avocado");
		data.add("Banana");
		data.add("Cranberrie, Dried");
		data.add("Coconut");
		data.add("Kiwano");
		data.add("Lemon");
		data.add("Papaya");
		data.add("Cactus Pear");
		data.add("Cherimoya");
		data.add("Clementine");
		data.add("Date");
		data.add("Grapefruit");
		data.add("Kiwifruit");
		data.add("Orange");
		data.add("Passion Fruit");
		data.add("Pear");
		data.add("Persimmons");
		data.add("Pummelo");
		data.add("Red Banana");
		data.add("Red Currant");
		data.add("Sharon Fruit");
		data.add("Tangerine");
		data.add("");
		data.add("Apricot");
		data.add("Barbados Cherry");
		data.add("Bitter Melon");
		data.add("Cherimoya");
		data.add("Honeydew");
		data.add("Jackfruit");
		data.add("Limes");
		data.add("Lychee");
		data.add("Mango");
		data.add("Oranges ");
		data.add("Pineapple");
		data.add("Strawberry");
		data.add("Apricot");
		data.add("Asian Pear");
		data.add("Barbados Cherry");
		data.add("Black Currant");
		data.add("Blackberry");
		data.add("Blueberry");
		data.add("Boysenberry");
		data.add("Breadfruit");
		data.add("Cantaloupe");
		data.add("Casaba Melon");
		data.add("Champagne Grape");
		data.add("Cherry");
		data.add("Cherry, Sour");
		data.add("Crenshaw Melon");
		data.add("Durian");
		data.add("Elderberry");
		data.add("Figs");
		data.add("Grapefruit");
		data.add("Grapes");
		data.add("Honeydew Melon");
		data.add("Jackfruit");
		data.add("Key Lime");
		data.add("Limes");
		data.add("Loganberrie");
		data.add("Longan");
		data.add("Loquat");
		data.add("Lychee");
		data.add("Mulberry");
		data.add("Nectarine");
		data.add("Olallieberry");
		data.add("Passion Fruit");
		data.add("Peach");
		data.add("Persian Melon");
		data.add("Plums");
		data.add("Raspberry");
		data.add("Sapodilla");
		data.add("Sapote");
		data.add("Strawberry");
		data.add("Sugar Apple");
		data.add("Watermelon");
		data.add("Asian Pear");
		data.add("Barbados Cherry");
		data.add("Cactus Pear");
		data.add("Cape Gooseberry");
		data.add("Crab Apples");
		data.add("Cranberry");
		data.add("Feijoa");
		data.add("Grapes");
		data.add("Guava");
		data.add("Huckleberry");
		data.add("Jujube");
		data.add("Key Lime");
		data.add("Kumquat");
		data.add("Muscadine Grape");
		data.add("Mushroom");
		data.add("Passion Fruit");
		data.add("Pear");
		data.add("Persimmon");
		data.add("Pineapple ");
		data.add("Pomegranate");
		data.add("Quince");
		data.add("Sapote");
		data.add("Sharon Fruit");
		data.add("Sugar Apple");
	}


}